In [1]:
import sys

from collections import defaultdict

import numpy as np
import pandas as pd
import scipy.stats as ss
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

from tqdm.auto import tqdm as tqdm_auto
from tqdm.notebook import tqdm

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader
import pytorch_lightning as pl

In [2]:
tqdm.pandas()

In [3]:
from shuffle_dinucl import shuffle_seq, shuffle_seq_dinucl

In [8]:
sys.path.append("../../predictor/model")
import utrdata_cl as utrdata
from pl_regressor import RNARegressor

## Creating dataset

In [9]:
SEQUENCE_N = 1_000_000

In [10]:
CELLTYPE_CODES_UTR3 = {"c1": 0,
                       "c2": 1,
                       "c4": 2,
                       "c6": 3,
                       "c17": 4,
                       "c13": 5,
                       #"c10": 6
                      }

CELLTYPE_CODES_UTR5 = {"c1": 0,
                       "c2": 1,
                       "c4": 2,
                       "c6": 3,
                       "c17": 4}

In [11]:
#src_seqs = pd.Series(pd.read_csv("../../data/raw/UTR5_sequence_counts_05_23_23.tsv", sep="\t", index_col=0, header=[0, 1, 2]).index.values)
src_seqs = pd.read_csv("../../data/UTR3_zinb_norm_singleref_2023-05-23.csv")["seq"].drop_duplicates()
src_seqs

0         TGCAGTTTTGACCTCCCAGGCTCAAGCGATCCTCCTGCCTCAGCCT...
10        ATCAAAAAGCAGGCCAGATTCTAATCAAAATCAGGTAAATTTTAAT...
20        ATTTTAGTTTGCCCAAATAATATCTTGAAAATGCTCTGAATTTTAC...
30        TTTCCCTTTTTCCCTCCCTCTATTCTCTTCACTAACATTGGAAATT...
40        TTCCTTCAGAGAATTCTCCTTTTCTTCTATGTTTCTGACTGCAATA...
                                ...
284210    AATGGTAAAGATTTTTACTCAGTGTGTGCTGAAACACTAAATTAAA...
284220    GCTAAAGCATTGCTTATTCAGTGGTATTCAGTAGATAAGATCTATT...
284230    TGTGCTTCCTAAGAGTACAAACCTGAGCATATGTCCAGGCTTGCAA...
284240    TAGGTGGTGATCTTAAATGGGTGAGATGGAACGAGAGCACACATTA...
284250    AGGAGGCAACTGTGGCATTGCTTCCTTAACCAGCTCATGGTGTGTG...
Name: seq, Length: 28426, dtype: object

In [12]:
np.random.seed(777)
sampled = src_seqs.sample(SEQUENCE_N, replace=True)
mononucl_shuffle = sampled.progress_apply(shuffle_seq)
dinucl_shuffle = sampled.progress_apply(shuffle_seq_dinucl)

  0%|          | 0/1000000 [00:00<?, ?it/s]

  0%|          | 0/1000000 [00:00<?, ?it/s]

In [13]:
seqs = pd.concat([pd.DataFrame({"seq": mononucl_shuffle, "shuffle": "mono"}), 
                  pd.DataFrame({"seq": dinucl_shuffle, "shuffle": "di"})]).reset_index(drop=True)
seqs

                                                       seq shuffle
0        GAATGAAACGAATATAACTACTAATTAACTATATTAATTCTTTTAA...    mono
1        TTCACGTCTCGTTTATGCAGCCATTGTACTTTGACTTGTGAATAAG...    mono
2        CTATATACAGTCCACGATCTTTTTCCTGGATTTACCTCAGACTAAT...    mono
3        AATCCAAGGGCACCGAGGAAATCGGCCCCCCTGAGAAAACTCCACG...    mono
4        GAATATCCAGCGTGTGATCGGCATCTGTTGCTTGTATAAAATTAGA...    mono
...                                                    ...     ...
1999995  GGGCTTGTAATGTCCTAATCAGAAAGTTAGAGACCCCCTCGAGTTC...      di
1999996  GTCCAGCAATCTGTGGTCCTTTAATCAACCCACCAGGCCTGGTCCA...      di
1999997  GCATTTATGTCAAATGATAAAAAACCTCATGGTTGACTAAGCTACT...      di
1999998  ACTGGTGCATTGTGTATTCCATCTGAACTGCCATTAGGTCAGCAAG...      di
1999999  ATGGACCATTACCCGCCGACCTGTTCTTTGGCGGATAAATTTTAGG...      di

[2000000 rows x 2 columns]

In [14]:
df = []
for ct_code in CELLTYPE_CODES_UTR3.keys():
    subdf = seqs.copy()
    subdf["cell_type"] = ct_code
    df.append(subdf)
df = pd.concat(df).sort_values(by=["shuffle", "seq", "cell_type"]).reset_index(drop=True)
df

                                                        seq shuffle cell_type
0         AAAAAAAAAAAAAAAGTTCTTTGTAGGACAAACCAGGCATCTTGGA...      di        c1
1         AAAAAAAAAAAAAAAGTTCTTTGTAGGACAAACCAGGCATCTTGGA...      di       c13
2         AAAAAAAAAAAAAAAGTTCTTTGTAGGACAAACCAGGCATCTTGGA...      di       c17
3         AAAAAAAAAAAAAAAGTTCTTTGTAGGACAAACCAGGCATCTTGGA...      di        c2
4         AAAAAAAAAAAAAAAGTTCTTTGTAGGACAAACCAGGCATCTTGGA...      di        c4
...                                                     ...     ...       ...
11999995  TTTTTTTTTTTTTATCGCGATTCTATTTTTATGTTTCTTTGAAACA...    mono       c13
11999996  TTTTTTTTTTTTTATCGCGATTCTATTTTTATGTTTCTTTGAAACA...    mono       c17
11999997  TTTTTTTTTTTTTATCGCGATTCTATTTTTATGTTTCTTTGAAACA...    mono        c2
11999998  TTTTTTTTTTTTTATCGCGATTCTATTTTTATGTTTCTTTGAAACA...    mono        c4
11999999  TTTTTTTTTTTTTATCGCGATTCTATTTTTATGTTTCTTTGAAACA...    mono        c6

[12000000 rows x 3 columns]

In [15]:
df["diff"] = 0.0
df["mass_center"] = 0.0

In [16]:
batch_size = 1024

In [17]:
num_workers = 32

In [18]:
generated_set = utrdata.UTRData(
    df=df,
    features=("sequence", "positional", "conditions"),
    construct_type="utr3",
    augment=False,
    augment_test_time=False,
    augment_kws=dict(
        extend_left=0,
        extend_right=0,
        shift_left=0,
        shift_right=0,
        revcomp=False,
    ),
)

In [19]:
# Creating DataLoaders
dl_gen = DataLoader(
    generated_set,
    batch_size=batch_size,
    num_workers=num_workers,
    shuffle=False,
    drop_last=False
)

In [22]:
ckpt_path = "../../predictor/regression_multiple/saved_models/model-utr3-deltas-epoch=9-step=1330.ckpt"

In [23]:
progressbar_callback = pl.callbacks.TQDMProgressBar(refresh_rate=0.5)
trainer = pl.Trainer(
    callbacks=[progressbar_callback],
    logger=False,
    accelerator="gpu",
    devices=1,
    deterministic=True,
    # gradient_clip_val=1e-5,
    # gradient_clip_algorithm="norm",
)

loaded_model = RNARegressor.load_from_checkpoint(ckpt_path)
prediction = trainer.predict(model=loaded_model, dataloaders=dl_gen)

gen_pred, _ = zip(*prediction)
gen_pred = torch.concat(gen_pred)
gen_pred = gen_pred.numpy()

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
You are using a CUDA device ('NVIDIA GeForce RTX 3090') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

Predicting: 0it [00:00, ?it/s]

In [24]:
gen_pred

array([[-2.3313530e-02,  2.4649439e+00],
       [ 2.7435645e-03,  2.4954305e+00],
       [ 3.6473878e-02,  2.4974866e+00],
       ...,
       [ 3.6264602e-02,  2.7656243e+00],
       [ 1.2395382e-02,  2.8494470e+00],
       [-8.7352525e-03,  2.7446942e+00]], dtype=float32)

In [25]:
score_df = df[["seq", "shuffle", "cell_type"]].copy()
score_df["pred_mass_center"] = gen_pred[:, 1]

In [26]:
score_df.to_csv("shuffle_result_utr3.csv.gz", index=False, compression="gzip")

In [27]:
score_df_pivot = score_df.pivot(index=["seq", "shuffle"], columns="cell_type", values="pred_mass_center").reset_index()
score_df_pivot

cell_type,seq,shuffle,c1,c13,c17,c2,c4,c6
0,AAAAAAAAAAAAAAAGTTCTTTGTAGGACAAACCAGGCATCTTGGA...,di,2.464944,2.495430,2.497487,2.442997,2.429699,2.413056
1,AAAAAAAAAAAAGGGTTTTGTTTAAAAAAAAATTCCCTAAACTCAC...,di,2.526143,2.560956,2.615242,2.562774,2.528626,2.661278
2,AAAAAAAAAAAAGTCAAAACAAATGTGGATGTCCCATGCTACTTCA...,di,2.308911,2.413520,2.360501,2.281934,2.448867,2.424832
3,AAAAAAAAAAAATTCAGGCACTGGCAAGGCTAACCGGTATTAACTC...,di,2.369751,2.455158,2.223603,2.324544,2.210814,2.433906
4,AAAAAAAAAAACACAGCCATTTATAATCTACTAAAGGATTCACATG...,di,2.538812,2.540170,2.650819,2.571809,2.569180,2.662145
...,...,...,...,...,...,...,...,...
1999995,TTTTTTTTTTTTCTTTTTCTATCTTGGACAGCTCCCCAGCTTCCGA...,di,2.764470,2.720094,3.039727,2.853697,2.947508,2.905812
1999996,TTTTTTTTTTTTTATCGCGATTCTATTTTTATGTTTCTTTGAAACA...,mono,2.956111,2.642194,2.779320,2.765624,2.849447,2.744694
1999997,TTTTTTTTTTTTTCAACCCAAGTCTGTGTCTAACCCTTGACAAAGT...,di,2.721936,2.605807,2.755110,2.652154,2.684300,2.495613
1999998,TTTTTTTTTTTTTGTCCCACAGAAGAATTTCCAGACACCCCTTTTA...,di,2.867949,2.701476,2.976445,2.848458,2.818522,2.894872
1999999,TTTTTTTTTTTTTTTTAAATAGCTTGATTGGAAAAGGTTAGGCTTC...,di,2.941038,2.695581,3.073126,2.921532,2.945261,2.965689

In [28]:
score_df_pivot.to_csv("shuffle_result_pivot_utr3.csv.gz", index=False, compression="gzip")

In [29]:
score_df_sample = score_df.iloc[:500000]

In [30]:
score_df_sample

,seq,shuffle,cell_type,pred_mass_center
0,AAAAAAAAAAAAAAAGTTCTTTGTAGGACAAACCAGGCATCTTGGA...,di,c1,2.464944
1,AAAAAAAAAAAAAAAGTTCTTTGTAGGACAAACCAGGCATCTTGGA...,di,c13,2.495430
2,AAAAAAAAAAAAAAAGTTCTTTGTAGGACAAACCAGGCATCTTGGA...,di,c17,2.497487
3,AAAAAAAAAAAAAAAGTTCTTTGTAGGACAAACCAGGCATCTTGGA...,di,c2,2.442997
4,AAAAAAAAAAAAAAAGTTCTTTGTAGGACAAACCAGGCATCTTGGA...,di,c4,2.429699
...,...,...,...,...
499995,AATTTCCAATCCGCTAGTCCTGAAGTGGGAATCAAAATTGGCCTGG...,di,c2,2.631828
499996,AATTTCCAATCCGCTAGTCCTGAAGTGGGAATCAAAATTGGCCTGG...,di,c4,2.672354
499997,AATTTCCAATCCGCTAGTCCTGAAGTGGGAATCAAAATTGGCCTGG...,di,c6,2.610172
499998,AATTTCCAATCTATCACCCCCGCCTGCATATTGAGGGATGTATCTA...,di,c1,2.664955
499999,AATTTCCAATCTATCACCCCCGCCTGCATATTGAGGGATGTATCTA...,di,c13,2.611268

In [31]:
score_df_sample["a"] = score_df_sample["seq"].str.count("A")
score_df_sample["c"] = score_df_sample["seq"].str.count("C")
score_df_sample["g"] = score_df_sample["seq"].str.count("G")
score_df_sample["t"] = score_df_sample["seq"].str.count("T")
score_df_sample

/tmp/ipykernel_2926375/2563659270.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  score_df_sample["a"] = score_df_sample["seq"].str.count("A")
/tmp/ipykernel_2926375/2563659270.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  score_df_sample["c"] = score_df_sample["seq"].str.count("C")
/tmp/ipykernel_2926375/2563659270.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  score_df_sample["g"] = score_df_sample["seq"].str.count("G")
/tmp/ipykernel_2926375/2563659270.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  score_df_sample["t"] = score_df_sample["seq"].str.count("T")

,seq,shuffle,cell_type,pred_mass_center,a,c,g,t
0,AAAAAAAAAAAAAAAGTTCTTTGTAGGACAAACCAGGCATCTTGGA...,di,c1,2.464944,74,40,53,73
1,AAAAAAAAAAAAAAAGTTCTTTGTAGGACAAACCAGGCATCTTGGA...,di,c13,2.495430,74,40,53,73
2,AAAAAAAAAAAAAAAGTTCTTTGTAGGACAAACCAGGCATCTTGGA...,di,c17,2.497487,74,40,53,73
3,AAAAAAAAAAAAAAAGTTCTTTGTAGGACAAACCAGGCATCTTGGA...,di,c2,2.442997,74,40,53,73
4,AAAAAAAAAAAAAAAGTTCTTTGTAGGACAAACCAGGCATCTTGGA...,di,c4,2.429699,74,40,53,73
...,...,...,...,...,...,...,...,...
499995,AATTTCCAATCCGCTAGTCCTGAAGTGGGAATCAAAATTGGCCTGG...,di,c2,2.631828,60,40,50,90
499996,AATTTCCAATCCGCTAGTCCTGAAGTGGGAATCAAAATTGGCCTGG...,di,c4,2.672354,60,40,50,90
499997,AATTTCCAATCCGCTAGTCCTGAAGTGGGAATCAAAATTGGCCTGG...,di,c6,2.610172,60,40,50,90
499998,AATTTCCAATCTATCACCCCCGCCTGCATATTGAGGGATGTATCTA...,di,c1,2.664955,65,57,45,73
499999,AATTTCCAATCTATCACCCCCGCCTGCATATTGAGGGATGTATCTA...,di,c13,2.611268,65,57,45,73

---