In [1]:
import sys
import os
import glob

import re

import itertools

import numpy as np
import pandas as pd

from tqdm.notebook import tqdm

import torch
from torch.utils.data import DataLoader
import pytorch_lightning as pl

In [2]:
sys.path.append("../model/")
import utrdata_cl as utrdata
from legnet import LegNetClassifier
from pl_regressor import RNARegressor

## Loading data

In [3]:
utr_type = "utr5"

In [4]:
if utr_type == "utr5":
    MODEL_PATH = "../regression_multiple/saved_models/model-utr5-deltas-epoch=9-step=840.ckpt"
elif utr_type == "utr3":
    MODEL_PATH = "../regression_multiple/saved_models/model-utr3-deltas-epoch=9-step=1330.ckpt"
else:
    raise ValueError

In [5]:
PATH_FROM = f"./{utr_type.upper()}_zscores_2024-06-04.csv"
df = pd.read_csv(PATH_FROM)

In [6]:
assert (df["seq"] == df["seq"].str.upper()).all()

In [7]:
ct_classes = df["cell_type"].unique()
num_classes = ct_classes.shape[0]
num_classes

5

In [8]:
batch_size = 1024
num_workers = 32

In [9]:
test_set = utrdata.UTRData(
    df=df,
    predict_cols=[],
    features=("sequence", "positional", "conditions"),
    construct_type=utr_type,
    augment=False,
    augment_test_time=False,
    augment_kws=dict(
        extend_left=0,
        extend_right=0,
        shift_left=0,
        shift_right=0,
        revcomp=False,
    ),
)
dl_test = DataLoader(
    test_set,
    batch_size=batch_size,
    num_workers=num_workers,
    shuffle=False,
    drop_last=False
)

model = RNARegressor.load_from_checkpoint(MODEL_PATH)
trainer = pl.Trainer(
    callbacks=[pl.callbacks.TQDMProgressBar(refresh_rate=0.5)],
    logger=False,
    accelerator="gpu",
    devices=[0],
    deterministic=True,
    num_sanity_val_steps=0,
)
prediction = trainer.predict(model=model, dataloaders=dl_test)
test_pred, test_real = zip(*prediction)
test_pred = torch.concat(test_pred).numpy()
test_real = torch.concat(test_real).numpy()
df_pred = df.copy()
df_pred["pred_delta"] = test_pred[:, 0]
df_pred["pred_mass_center"] = test_pred[:, 1]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
You are using a CUDA device ('NVIDIA GeForce RTX 3090') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

Predicting: 0it [00:00, ?it/s]

In [10]:
df_pred

,seq,cell_type,1,2,3,4,mass_center,mass_center_mean,diff,zscore,mass_center_std,pred_delta,pred_mass_center
0,AAAAAAAATGTGACGGCGGCGGCGGCGGCGGCGGCGGCAGCGGCGG...,c1,614.0,395.0,685.0,815.0,2.677959,2.296948,0.381012,1.191578,0.319754,0.020646,2.235352
1,AAAAAAAATGTGACGGCGGCGGCGGCGGCGGCGGCGGCAGCGGCGG...,c17,3442.0,3260.0,2909.0,4201.0,2.569722,2.296948,0.272774,0.853076,0.319754,-0.073548,2.374466
2,AAAAAAAATGTGACGGCGGCGGCGGCGGCGGCGGCGGCAGCGGCGG...,c2,3384.0,2467.0,1713.0,1320.0,2.109072,2.296948,-0.187875,-0.587562,0.319754,0.003716,2.172375
3,AAAAAAAATGTGACGGCGGCGGCGGCGGCGGCGGCGGCAGCGGCGG...,c4,3926.0,1645.0,1375.0,933.0,1.913060,2.296948,-0.383888,-1.200572,0.319754,-0.008880,2.328300
4,AAAAAAAATGTGACGGCGGCGGCGGCGGCGGCGGCGGCAGCGGCGG...,c6,4475.0,2894.0,3129.0,2018.0,2.214925,2.296948,-0.082023,-0.256519,0.319754,-0.019559,2.336071
...,...,...,...,...,...,...,...,...,...,...,...,...,...
50865,TTTTTTGTGTGCGTGCACGTCCTCGTTATCGTGCATCCATGGCGCG...,c1,3743.0,3008.0,4050.0,4807.0,2.635636,2.490269,0.145367,1.232848,0.117911,-0.036285,2.368677
50866,TTTTTTGTGTGCGTGCACGTCCTCGTTATCGTGCATCCATGGCGCG...,c17,8932.0,12713.0,10469.0,9848.0,2.506005,2.490269,0.015737,0.133462,0.117911,0.054916,2.555843
50867,TTTTTTGTGTGCGTGCACGTCCTCGTTATCGTGCATCCATGGCGCG...,c2,9045.0,10634.0,12367.0,9488.0,2.536861,2.490269,0.046593,0.395149,0.117911,-0.022615,2.420760
50868,TTTTTTGTGTGCGTGCACGTCCTCGTTATCGTGCATCCATGGCGCG...,c4,15230.0,14372.0,13533.0,13944.0,2.458855,2.490269,-0.031413,-0.266416,0.117911,-0.016199,2.403863
50869,TTTTTTGTGTGCGTGCACGTCCTCGTTATCGTGCATCCATGGCGCG...,c6,10436.0,3150.0,4367.0,6943.0,2.313986,2.490269,-0.176283,-1.495043,0.117911,-0.065204,2.281163

## Adding metadata

In [11]:
df_src = pd.read_table(f"../../data/lib2/raw/{utr_type.upper()}_sequence_metadata_06_04_24.tsv", index_col=0)
df.index.name = "seq"

In [12]:
def get_tag_rowwise(row: pd.Series):
    ct1 = row['first_cell_line']
    ct2 = row['second_cell_line']
    if pd.isna(ct1):
        return {"direction": np.nan, "cell_types": np.nan}
    elif pd.isna(ct2):
        if ct1 in {"up", "down"}:
            return {"direction": ct1, "cell_types": np.nan}
        else:
            raise Exception
    else:
        return {"direction": np.nan, "cell_types": f"{ct1}-{ct2}"}

In [13]:
tags_df = df_src.apply(get_tag_rowwise, axis=1).apply(pd.Series)

### Info for diffusion

In [14]:
diffusion_files = glob.glob(f"../../generator/diffusion/generate/results/*{utr_type[-1]}UTR.csv")
diffusion_taken = []
for gen_result_file in tqdm(diffusion_files):
    bn = os.path.basename(gen_result_file)
    ct = re.match(r"cell_(c\d+)_epoch_\d+_\dUTR.csv", bn).group(1)
    gen_result_df = pd.read_csv(gen_result_file)
    gen_result_df = gen_result_df[gen_result_df["seq"].isin(set(df["seq"]))]
    gen_result_df["diffusion_cell_type"] = ct
    diffusion_taken.append(gen_result_df)
diffusion_taken = pd.concat(diffusion_taken).set_index("seq")

  0%|          | 0/4 [00:00<?, ?it/s]

In [15]:
diffusion_taken = diffusion_taken[~diffusion_taken.index.duplicated(keep=False)]

## Reshaping data

In [16]:
df_sub = df_pred.set_index(["seq", "cell_type"]).copy()
df_new = df_sub[["mass_center", "diff", "pred_mass_center", "pred_delta"]]
df_new = df_new.unstack(1).reorder_levels((1, 0), axis=1).sort_index(axis=1)

In [17]:
df_new["source"] = df_src["source"]
df_new["source_ext"] = df_src["name"]
df_new["diffusion_query"] = diffusion_taken["mass_center"]
df_new["diffusion_cell_type"] = diffusion_taken["diffusion_cell_type"]
df_new["direction"] = tags_df["direction"]
df_new["cell_types_directional"] = tags_df["cell_types"]
df_new["cell_types_ordered"] = np.nan

In [18]:
cell_types = ["c1", "c2", "c4", "c6", "c13", "c17"]
for ct1, ct2 in itertools.combinations(cell_types, 2):
    df_new.loc[df_new["cell_types_directional"] == f"{ct1}-{ct2}", "cell_types_ordered"] = f"{ct1}-{ct2}"
    df_new.loc[df_new["cell_types_directional"] == f"{ct1}-{ct2}", "direction"] = "up"
    df_new.loc[df_new["cell_types_directional"] == f"{ct2}-{ct1}", "cell_types_ordered"] = f"{ct1}-{ct2}"
    df_new.loc[df_new["cell_types_directional"] == f"{ct2}-{ct1}", "direction"] = "down"

In [19]:
df_new

cell_type                                                 c1              \
                                                        diff mass_center
seq
AAAAAAAATGTGACGGCGGCGGCGGCGGCGGCGGCGGCAGCGGCGGCGGC  0.381012    2.677959
AAAAAATGGAGCGTGCGGCCTTGGCTGGTGGAGGAGGCGCAGGCAGCCCC -0.023875    2.591365
AAAAAATGGAGGCGGAGCTGCGGCGGCGGCGGCGGCTGTGGCGGGACGTC  0.213143    2.419520
AAAAAATGGCAGCGAGGGCGTTGGCGACGGCTGAGAGCGGAGCCGGCGTG  0.005109    2.676759
AAAAAGAGGCCTGGGCCGGGAGTCCCCGCCCCTGGGCCCAGCCCTGGCCG  0.182111    2.467139
...                                                      ...         ...
TTTTTCGGCGGCGGGTGGGGGGGGGCGGTTTCGTTCGTGGTCCTTTGTTT -0.004011    2.637498
TTTTTCTTCCTCCGCCCCTTCCTGGTAGAGGAGAAGGCGCGGGTGGGGGA -0.043220    2.719421
TTTTTGCGTGTGCGCTGTGACTGGTGCTCCGTTTTCCTCGCTCATGGTGG  0.239196    2.513599
TTTTTTCTGCTGCAGGCGGAGCGGCGCGCGGAGGAGGCGCCGGGAGCCGC  0.124972    2.735958
TTTTTTGTGTGCGTGCACGTCCTCGTTATCGTGCATCCATGGCGCGTGGG  0.145367    2.635636

cell_type                                                      \
                                                   pred_delta
seq
AAAAAAAATGTGACGGCGGCGGCGGCGGCGGCGGCGGCAGCGGCGGCGGC   0.020646
AAAAAATGGAGCGTGCGGCCTTGGCTGGTGGAGGAGGCGCAGGCAGCCCC   0.017169
AAAAAATGGAGGCGGAGCTGCGGCGGCGGCGGCGGCTGTGGCGGGACGTC   0.018511
AAAAAATGGCAGCGAGGGCGTTGGCGACGGCTGAGAGCGGAGCCGGCGTG   0.032640
AAAAAGAGGCCTGGGCCGGGAGTCCCCGCCCCTGGGCCCAGCCCTGGCCG  -0.004608
...                                                       ...
TTTTTCGGCGGCGGGTGGGGGGGGGCGGTTTCGTTCGTGGTCCTTTGTTT   0.001343
TTTTTCTTCCTCCGCCCCTTCCTGGTAGAGGAGAAGGCGCGGGTGGGGGA   0.007573
TTTTTGCGTGTGCGCTGTGACTGGTGCTCCGTTTTCCTCGCTCATGGTGG  -0.013145
TTTTTTCTGCTGCAGGCGGAGCGGCGCGCGGAGGAGGCGCCGGGAGCCGC  -0.023647
TTTTTTGTGTGCGTGCACGTCCTCGTTATCGTGCATCCATGGCGCGTGGG  -0.036285

cell_type                                                                 c17  \
                                                   pred_mass_center      diff
seq
AAAAAAAATGTGACGGCGGCGGCGGCGGCGGCGGCGGCAGCGGCGGCGGC         2.235352  0.272774
AAAAAATGGAGCGTGCGGCCTTGGCTGGTGGAGGAGGCGCAGGCAGCCCC         2.307761 -0.240933
AAAAAATGGAGGCGGAGCTGCGGCGGCGGCGGCGGCTGTGGCGGGACGTC         2.419005 -0.058341
AAAAAATGGCAGCGAGGGCGTTGGCGACGGCTGAGAGCGGAGCCGGCGTG         2.466333  0.100583
AAAAAGAGGCCTGGGCCGGGAGTCCCCGCCCCTGGGCCCAGCCCTGGCCG         2.158932 -0.375713
...                                                             ...       ...
TTTTTCGGCGGCGGGTGGGGGGGGGCGGTTTCGTTCGTGGTCCTTTGTTT         2.642587  0.216876
TTTTTCTTCCTCCGCCCCTTCCTGGTAGAGGAGAAGGCGCGGGTGGGGGA         2.633624  0.284050
TTTTTGCGTGTGCGCTGTGACTGGTGCTCCGTTTTCCTCGCTCATGGTGG         2.406738 -0.013046
TTTTTTCTGCTGCAGGCGGAGCGGCGCGCGGAGGAGGCGCCGGGAGCCGC         2.684644  0.031983
TTTTTTGTGTGCGTGCACGTCCTCGTTATCGTGCATCCATGGCGCGTGGG         2.368677  0.015737

cell_type                                                                  \
                                                   mass_center pred_delta
seq
AAAAAAAATGTGACGGCGGCGGCGGCGGCGGCGGCGGCAGCGGCGGCGGC    2.569722  -0.073548
AAAAAATGGAGCGTGCGGCCTTGGCTGGTGGAGGAGGCGCAGGCAGCCCC    2.374306  -0.045304
AAAAAATGGAGGCGGAGCTGCGGCGGCGGCGGCGGCTGTGGCGGGACGTC    2.148036  -0.051771
AAAAAATGGCAGCGAGGGCGTTGGCGACGGCTGAGAGCGGAGCCGGCGTG    2.772232  -0.031547
AAAAAGAGGCCTGGGCCGGGAGTCCCCGCCCCTGGGCCCAGCCCTGGCCG    1.909315  -0.109573
...                                                        ...        ...
TTTTTCGGCGGCGGGTGGGGGGGGGCGGTTTCGTTCGTGGTCCTTTGTTT    2.858386   0.079729
TTTTTCTTCCTCCGCCCCTTCCTGGTAGAGGAGAAGGCGCGGGTGGGGGA    3.046692   0.045410
TTTTTGCGTGTGCGCTGTGACTGGTGCTCCGTTTTCCTCGCTCATGGTGG    2.261358   0.045314
TTTTTTCTGCTGCAGGCGGAGCGGCGCGCGGAGGAGGCGCCGGGAGCCGC    2.642969   0.073584
TTTTTTGTGTGCGTGCACGTCCTCGTTATCGTGCATCCATGGCGCGTGGG    2.506005   0.054916

cell_type                                                                  c2  \
                                                   pred_mass_center      diff
seq
AAAAAAAATGTGACGGCGGCGGCGGCGGCGGCGGCGGCAGCGGCGGCGGC         2.374466 -0.187875
AAAAAATGGAGCGTGCGGCCTTGGCTGGTGGAGGAGGCGCAGGCAGCCCC         2.408771  0.179457
AAAAAATGGAGGCGGAGCTGCGGCGGCGGCGGCGGCTGTGGCGGGACGTC         2.549825 -0.318362
AAAAAATGGCAGCGAGGGCGTTGGCGACGGCTGAGAGCGGAGCCGGCGTG         2.519254 -0.064995
AAAAAGAGGCCTGGGCCGGGAGTCCCCGCCCCTGGGCCCAGCCCTGGCCG         1.974816  0.122360
...                                                             ...       ...
TTTTTCGGCGGCGGGTGGGGGGGGGCGGTTTCGTTCGTGGTCCTTTGTTT         2.761328 -0.116228
TTTTTCTTCCTCCGCCCCTTCCTGGTAGAGGAGAAGGCGCGGGTGGGGGA         2.730166 -0.270071
TTTTTGCGTGTGCGCTGTGACTGGTGCTCCGTTTTCCTCGCTCATGGTGG         2.512556 -0.046078
TTTTTTCTGCTGCAGGCGGAGCGGCGCGCGGAGGAGGCGCCGGGAGCCGC         2.824139 -0.208998
TTTTTTGTGTGCGTGCACGTCCTCGTTATCGTGCATCCATGGCGCGTGGG         2.555843  0.046593

cell_type                                                       ...  \
                                                   mass_center  ...
seq                                                             ...
AAAAAAAATGTGACGGCGGCGGCGGCGGCGGCGGCGGCAGCGGCGGCGGC    2.109072  ...
AAAAAATGGAGCGTGCGGCCTTGGCTGGTGGAGGAGGCGCAGGCAGCCCC    2.794696  ...
AAAAAATGGAGGCGGAGCTGCGGCGGCGGCGGCGGCTGTGGCGGGACGTC    1.888015  ...
AAAAAATGGCAGCGAGGGCGTTGGCGACGGCTGAGAGCGGAGCCGGCGTG    2.606655  ...
AAAAAGAGGCCTGGGCCGGGAGTCCCCGCCCCTGGGCCCAGCCCTGGCCG    2.407388  ...
...                                                        ...  ...
TTTTTCGGCGGCGGGTGGGGGGGGGCGGTTTCGTTCGTGGTCCTTTGTTT    2.525281  ...
TTTTTCTTCCTCCGCCCCTTCCTGGTAGAGGAGAAGGCGCGGGTGGGGGA    2.492571  ...
TTTTTGCGTGTGCGCTGTGACTGGTGCTCCGTTTTCCTCGCTCATGGTGG    2.228325  ...
TTTTTTCTGCTGCAGGCGGAGCGGCGCGCGGAGGAGGCGCCGGGAGCCGC    2.401988  ...
TTTTTTGTGTGCGTGCACGTCCTCGTTATCGTGCATCCATGGCGCGTGGG    2.536861  ...

cell_type                                                   c6             \
                                                   mass_center pred_delta
seq
AAAAAAAATGTGACGGCGGCGGCGGCGGCGGCGGCGGCAGCGGCGGCGGC    2.214925  -0.019559
AAAAAATGGAGCGTGCGGCCTTGGCTGGTGGAGGAGGCGCAGGCAGCCCC    2.470830  -0.042557
AAAAAATGGAGGCGGAGCTGCGGCGGCGGCGGCGGCTGTGGCGGGACGTC    2.404858  -0.000516
AAAAAATGGCAGCGAGGGCGTTGGCGACGGCTGAGAGCGGAGCCGGCGTG    2.800523  -0.002092
AAAAAGAGGCCTGGGCCGGGAGTCCCCGCCCCTGGGCCCAGCCCTGGCCG    2.546918  -0.116847
...                                                        ...        ...
TTTTTCGGCGGCGGGTGGGGGGGGGCGGTTTCGTTCGTGGTCCTTTGTTT    2.483388  -0.030129
TTTTTCTTCCTCCGCCCCTTCCTGGTAGAGGAGAAGGCGCGGGTGGGGGA    2.913750  -0.000366
TTTTTGCGTGTGCGCTGTGACTGGTGCTCCGTTTTCCTCGCTCATGGTGG    2.303710  -0.031353
TTTTTTCTGCTGCAGGCGGAGCGGCGCGCGGAGGAGGCGCCGGGAGCCGC    2.630460   0.074046
TTTTTTGTGTGCGTGCACGTCCTCGTTATCGTGCATCCATGGCGCGTGGG    2.313986  -0.065204

cell_type                                                            \
                                                   pred_mass_center
seq
AAAAAAAATGTGACGGCGGCGGCGGCGGCGGCGGCGGCAGCGGCGGCGGC         2.336071
AAAAAATGGAGCGTGCGGCCTTGGCTGGTGGAGGAGGCGCAGGCAGCCCC         2.366087
AAAAAATGGAGGCGGAGCTGCGGCGGCGGCGGCGGCTGTGGCGGGACGTC         2.520375
AAAAAATGGCAGCGAGGGCGTTGGCGACGGCTGAGAGCGGAGCCGGCGTG         2.483383
AAAAAGAGGCCTGGGCCGGGAGTCCCCGCCCCTGGGCCCAGCCCTGGCCG         2.022552
...                                                             ...
TTTTTCGGCGGCGGGTGGGGGGGGGCGGTTTCGTTCGTGGTCCTTTGTTT         2.547150
TTTTTCTTCCTCCGCCCCTTCCTGGTAGAGGAGAAGGCGCGGGTGGGGGA         2.632445
TTTTTGCGTGTGCGCTGTGACTGGTGCTCCGTTTTCCTCGCTCATGGTGG         2.366170
TTTTTTCTGCTGCAGGCGGAGCGGCGCGCGGAGGAGGCGCCGGGAGCCGC         2.796438
TTTTTTGTGTGCGTGCACGTCCTCGTTATCGTGCATCCATGGCGCGTGGG         2.281163

cell_type                                                              source  \

seq
AAAAAAAATGTGACGGCGGCGGCGGCGGCGGCGGCGGCAGCGGCGGCGGC  diffusion-tissue-specific
AAAAAATGGAGCGTGCGGCCTTGGCTGGTGGAGGAGGCGCAGGCAGCCCC  diffusion-tissue-specific
AAAAAATGGAGGCGGAGCTGCGGCGGCGGCGGCGGCTGTGGCGGGACGTC  diffusion-tissue-specific
AAAAAATGGCAGCGAGGGCGTTGGCGACGGCTGAGAGCGGAGCCGGCGTG  diffusion-tissue-specific
AAAAAGAGGCCTGGGCCGGGAGTCCCCGCCCCTGGGCCCAGCCCTGGCCG  diffusion-tissue-specific
...                                                                       ...
TTTTTCGGCGGCGGGTGGGGGGGGGCGGTTTCGTTCGTGGTCCTTTGTTT  diffusion-tissue-specific
TTTTTCTTCCTCCGCCCCTTCCTGGTAGAGGAGAAGGCGCGGGTGGGGGA  diffusion-tissue-specific
TTTTTGCGTGTGCGCTGTGACTGGTGCTCCGTTTTCCTCGCTCATGGTGG                     random
TTTTTTCTGCTGCAGGCGGAGCGGCGCGCGGAGGAGGCGCCGGGAGCCGC  diffusion-tissue-specific
TTTTTTGTGTGCGTGCACGTCCTCGTTATCGTGCATCCATGGCGCGTGGG          genetic_algorithm

cell_type                                                                                     comment  \

seq
AAAAAAAATGTGACGGCGGCGGCGGCGGCGGCGGCGGCAGCGGCGGCGGC  AAAAAAAATGTGACGGCGGCGGCGGCGGCGGCGGCGGCAGCGGCGG...
AAAAAATGGAGCGTGCGGCCTTGGCTGGTGGAGGAGGCGCAGGCAGCCCC  AAAAAATGGAGCGTGCGGCCTTGGCTGGTGGAGGAGGCGCAGGCAG...
AAAAAATGGAGGCGGAGCTGCGGCGGCGGCGGCGGCTGTGGCGGGACGTC  AAAAAATGGAGGCGGAGCTGCGGCGGCGGCGGCGGCTGTGGCGGGA...
AAAAAATGGCAGCGAGGGCGTTGGCGACGGCTGAGAGCGGAGCCGGCGTG  AAAAAATGGCAGCGAGGGCGTTGGCGACGGCTGAGAGCGGAGCCGG...
AAAAAGAGGCCTGGGCCGGGAGTCCCCGCCCCTGGGCCCAGCCCTGGCCG  AAAAAGAGGCCTGGGCCGGGAGTCCCCGCCCCTGGGCCCAGCCCTG...
...                                                                                               ...
TTTTTCGGCGGCGGGTGGGGGGGGGCGGTTTCGTTCGTGGTCCTTTGTTT  TTTTTCGGCGGCGGGTGGGGGGGGGCGGTTTCGTTCGTGGTCCTTT...
TTTTTCTTCCTCCGCCCCTTCCTGGTAGAGGAGAAGGCGCGGGTGGGGGA  TTTTTCTTCCTCCGCCCCTTCCTGGTAGAGGAGAAGGCGCGGGTGG...
TTTTTGCGTGTGCGCTGTGACTGGTGCTCCGTTTTCCTCGCTCATGGTGG  TTTTTGCGTGTGCGCTGTGACTGGTGCTCCGTTTTCCTCGCTCATG...
TTTTTTCTGCTGCAGGCGGAGCGGCGCGCGGAGGAGGCGCCGGGAGCCGC  TTTTTTCTGCTGCAGGCGGAGCGGCGCGCGGAGGAGGCGCCGGGAG...
TTTTTTGTGTGCGTGCACGTCCTCGTTATCGTGCATCCATGGCGCGTGGG  TTTTTTGTGTGCGTGCACGTCCTCGTTATCGTGCATCCATGGCGCG...

cell_type                                          diffusion_query  \

seq
AAAAAAAATGTGACGGCGGCGGCGGCGGCGGCGGCGGCAGCGGCGGCGGC        2.038932
AAAAAATGGAGCGTGCGGCCTTGGCTGGTGGAGGAGGCGCAGGCAGCCCC        2.143708
AAAAAATGGAGGCGGAGCTGCGGCGGCGGCGGCGGCTGTGGCGGGACGTC        2.425079
AAAAAATGGCAGCGAGGGCGTTGGCGACGGCTGAGAGCGGAGCCGGCGTG        2.445176
AAAAAGAGGCCTGGGCCGGGAGTCCCCGCCCCTGGGCCCAGCCCTGGCCG        2.046536
...                                                            ...
TTTTTCGGCGGCGGGTGGGGGGGGGCGGTTTCGTTCGTGGTCCTTTGTTT        2.886686
TTTTTCTTCCTCCGCCCCTTCCTGGTAGAGGAGAAGGCGCGGGTGGGGGA        2.852876
TTTTTGCGTGTGCGCTGTGACTGGTGCTCCGTTTTCCTCGCTCATGGTGG             NaN
TTTTTTCTGCTGCAGGCGGAGCGGCGCGCGGAGGAGGCGCCGGGAGCCGC        2.967216
TTTTTTGTGTGCGTGCACGTCCTCGTTATCGTGCATCCATGGCGCGTGGG             NaN

cell_type                                          diffusion_cell_type  \

seq
AAAAAAAATGTGACGGCGGCGGCGGCGGCGGCGGCGGCAGCGGCGGCGGC                  c4
AAAAAATGGAGCGTGCGGCCTTGGCTGGTGGAGGAGGCGCAGGCAGCCCC                  c4
AAAAAATGGAGGCGGAGCTGCGGCGGCGGCGGCGGCTGTGGCGGGACGTC                  c4
AAAAAATGGCAGCGAGGGCGTTGGCGACGGCTGAGAGCGGAGCCGGCGTG                  c4
AAAAAGAGGCCTGGGCCGGGAGTCCCCGCCCCTGGGCCCAGCCCTGGCCG                  c4
...                                                                ...
TTTTTCGGCGGCGGGTGGGGGGGGGCGGTTTCGTTCGTGGTCCTTTGTTT                  c4
TTTTTCTTCCTCCGCCCCTTCCTGGTAGAGGAGAAGGCGCGGGTGGGGGA                  c4
TTTTTGCGTGTGCGCTGTGACTGGTGCTCCGTTTTCCTCGCTCATGGTGG                 NaN
TTTTTTCTGCTGCAGGCGGAGCGGCGCGCGGAGGAGGCGCCGGGAGCCGC                  c6
TTTTTTGTGTGCGTGCACGTCCTCGTTATCGTGCATCCATGGCGCGTGGG                 NaN

cell_type                                          direction  \

seq
AAAAAAAATGTGACGGCGGCGGCGGCGGCGGCGGCGGCAGCGGCGGCGGC      down
AAAAAATGGAGCGTGCGGCCTTGGCTGGTGGAGGAGGCGCAGGCAGCCCC      down
AAAAAATGGAGGCGGAGCTGCGGCGGCGGCGGCGGCTGTGGCGGGACGTC      down
AAAAAATGGCAGCGAGGGCGTTGGCGACGGCTGAGAGCGGAGCCGGCGTG      down
AAAAAGAGGCCTGGGCCGGGAGTCCCCGCCCCTGGGCCCAGCCCTGGCCG        up
...                                                      ...
TTTTTCGGCGGCGGGTGGGGGGGGGCGGTTTCGTTCGTGGTCCTTTGTTT        up
TTTTTCTTCCTCCGCCCCTTCCTGGTAGAGGAGAAGGCGCGGGTGGGGGA        up
TTTTTGCGTGTGCGCTGTGACTGGTGCTCCGTTTTCCTCGCTCATGGTGG      down
TTTTTTCTGCTGCAGGCGGAGCGGCGCGCGGAGGAGGCGCCGGGAGCCGC      down
TTTTTTGTGTGCGTGCACGTCCTCGTTATCGTGCATCCATGGCGCGTGGG      down

cell_type                                          cell_types_directional  \

seq
AAAAAAAATGTGACGGCGGCGGCGGCGGCGGCGGCGGCAGCGGCGGCGGC                 c17-c2
AAAAAATGGAGCGTGCGGCCTTGGCTGGTGGAGGAGGCGCAGGCAGCCCC                  c4-c1
AAAAAATGGAGGCGGAGCTGCGGCGGCGGCGGCGGCTGTGGCGGGACGTC                  c4-c1
AAAAAATGGCAGCGAGGGCGTTGGCGACGGCTGAGAGCGGAGCCGGCGTG                  c4-c2
AAAAAGAGGCCTGGGCCGGGAGTCCCCGCCCCTGGGCCCAGCCCTGGCCG                 c2-c17
...                                                                   ...
TTTTTCGGCGGCGGGTGGGGGGGGGCGGTTTCGTTCGTGGTCCTTTGTTT                  c4-c6
TTTTTCTTCCTCCGCCCCTTCCTGGTAGAGGAGAAGGCGCGGGTGGGGGA                  c4-c6
TTTTTGCGTGTGCGCTGTGACTGGTGCTCCGTTTTCCTCGCTCATGGTGG                 c17-c4
TTTTTTCTGCTGCAGGCGGAGCGGCGCGCGGAGGAGGCGCCGGGAGCCGC                  c4-c2
TTTTTTGTGTGCGTGCACGTCCTCGTTATCGTGCATCCATGGCGCGTGGG                 c17-c6

cell_type                                          cell_types_ordered

seq
AAAAAAAATGTGACGGCGGCGGCGGCGGCGGCGGCGGCAGCGGCGGCGGC             c2-c17
AAAAAATGGAGCGTGCGGCCTTGGCTGGTGGAGGAGGCGCAGGCAGCCCC              c1-c4
AAAAAATGGAGGCGGAGCTGCGGCGGCGGCGGCGGCTGTGGCGGGACGTC              c1-c4
AAAAAATGGCAGCGAGGGCGTTGGCGACGGCTGAGAGCGGAGCCGGCGTG              c2-c4
AAAAAGAGGCCTGGGCCGGGAGTCCCCGCCCCTGGGCCCAGCCCTGGCCG             c2-c17
...                                                               ...
TTTTTCGGCGGCGGGTGGGGGGGGGCGGTTTCGTTCGTGGTCCTTTGTTT              c4-c6
TTTTTCTTCCTCCGCCCCTTCCTGGTAGAGGAGAAGGCGCGGGTGGGGGA              c4-c6
TTTTTGCGTGTGCGCTGTGACTGGTGCTCCGTTTTCCTCGCTCATGGTGG             c4-c17
TTTTTTCTGCTGCAGGCGGAGCGGCGCGCGGAGGAGGCGCCGGGAGCCGC              c2-c4
TTTTTTGTGTGCGTGCACGTCCTCGTTATCGTGCATCCATGGCGCGTGGG             c6-c17

[10174 rows x 27 columns]

In [20]:
df_new.to_parquet(f"{utr_type.upper()}_library2_preds.parquet")

---